#!/usr/bin/perl

use 5.34.0;
use utf8;
use warnings;
use autodie;

use DBI;

# Make this script into a website
print("Content-Type: text/html\n\n");

# Create the header
print( q*
<!DOCTYPE html lang=en>
<html lang="en">

<head>
<meta charset="utf-8">
<title>Organizer</title>
<meta name="description" content="Website to help organize Alan's life">
<meta name="author" content="Hans Alan Whitburn Haugen">

<!-- Mobile Specific Metas
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<meta name="viewport" content="width=device-width, initial-scale=1">
        *
);

# Setup the FONT
print( q*
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
        *
);

# Setup the CSS
print( q*
    <link rel="stylesheet" href="/css/normalize.css">
    <link rel="stylesheet" href="/css/skeleton.css">
        *
);

# Setup ajax
print (q*
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<style>
.dragbox {
  margin: 0 .2rem;
  font-size: 90%;
  white-space: nowrap;
  background: #F1F1F1;
  border: 1px solid #E1E1E1;
  border-radius: 4px;
  padding: 15px 0px;
  text-align: center;
};
</style>

    <script>

	function handleDragStart(e) {
	  this.style.opacity = '0.4';
	  this.style.border = '1px dotted #666';
	  this.style.padding = '3px';

	  dragSrcEl = this;

	  e.dataTransfer.effectAllowed = 'move';
	  e.dataTransfer.setData('text/html', this.innerHTML);

	  document.querySelectorAll('.dragbox').forEach(e => e.remove());

	  $("#action").append('<li class="dragbox">Drag item here to add to actions list …</li>');
	  $("#wait").append('<li class="dragbox">Drag item here to add to wait list …</li>');
	  $("#long-term").append('<li class="dragbox box">Drag item here to add to long term plans list …</li>');
		let items2 = document.querySelectorAll('.dragbox');
		items2.forEach(function (item) {
		  item.addEventListener('dragstart', handleDragStart);
		  item.addEventListener('dragover', handleDragOver);
		  item.addEventListener('dragend', handleDragEnd);
		  item.addEventListener('dragenter', handleDragEnter);
		  item.addEventListener('dragleave', handleDragLeave);
		  item.addEventListener('drop', handleDrop);
		});
	}

	function handleDragEnd(e) {
	  this.style.opacity = '1';
	  this.style.border = 0;
	  this.style.padding = '0px';

	  items.forEach(function (item) {
	      item.classList.remove('over');
	  });
	}

	function handleDragOver(e) {
	  e.preventDefault();
	  e.dataTransfer.effectAllowed = 'move';
	  e.dataTransfer.setData('text/html', this.innerHTML);
	  return false;
	}

	function handleDragEnter(e) {
	  this.classList.add('over');
	}

	function handleDragLeave(e) {
	  this.classList.remove('over');
	}

	function handleDrop(e) {
	  e.stopPropagation(); // stops the browser from redirecting.

	  var ID = dragSrcEl.childNodes[0].id;

	  dragSrcEl.innerHTML = this.innerHTML;
	  this.innerHTML = e.dataTransfer.getData('text/html');

	  if (this.classList.contains('dragbox'))
	  {
	      var list = 'inbox';

	      if (dragSrcEl.innerHTML.indexOf("action") !== -1)
	      {
		    list = 'action';
	      }
	      
	      if (dragSrcEl.innerHTML.indexOf("wait") !== -1)
	      {
		    list = 'wait';
	      }

	      if (dragSrcEl.innerHTML.indexOf("long term") !== -1)
	      {
		    list = 'long_term';
	      }

	      this.classList.remove('dragbox');
	      dragSrcEl.remove();

	      $.ajax({
	              type: 'POST',
	              url: '/cgi-bin/organize/remove_todo.pl',
	              data: { 'data_id': ID },
	              success: function(res) {

	          			    //alert(ID);

	          			    },
	          			    error: function() {alert("did not work: " + ID);}
	      });
	      $.ajax({
	              type: 'POST',
	              url: '/cgi-bin/organize/add_todo.pl',
	              data: { 'data_id': list },
	              success: function(res) {

	          			    //alert(ID);

	          			    },
	          			    error: function() {alert("did not work: " + ID);}
	      });
	  }

	  return false;
	}


            $(document).ready(function() {

		let items = document.querySelectorAll('.box');
		items.forEach(function (item) {
		  item.addEventListener('dragstart', handleDragStart);
		  item.addEventListener('dragover', handleDragOver);
		  item.addEventListener('dragend', handleDragEnd);
		  item.addEventListener('dragenter', handleDragEnter);
		  item.addEventListener('dragleave', handleDragLeave);
		  item.addEventListener('drop', handleDrop);
		});

                $("#add").click(function(){
                    var ID = document.getElementById('todo_input').value;
                    $.ajax({
                            type: 'POST',
                            url: '/cgi-bin/organize/ajax.pl',
                            data: { 'data_id': ID },
                            success: function(res) {

							$("#inbox").append('<li><input type="checkbox" /> ' + res.result);
							document.getElementById('todo_input').value = "";

                                                    },
                            error: function() {alert("did not work");}
                    });
                })

		    $('.is_done').each(function(index, object) {
		    $(this).on("click", function(){
			    var ID = object.id;
			    $.ajax({
				    type: 'POST',
				    url: '/cgi-bin/organize/ajax2.pl',
				    data: { 'data_id': ID },
				    success: function(res) {

							    //alert(ID);

							    },
							    error: function() {alert("did not work: " + ID);}
			    });
			    });
			});
            })



        </script>
*
);

# End of header
print("</head>");

# Start body
print(q*
<body>
    <div class="container">
      <div class="row">
        <div class="six columns" style="margin-top: 15%">
        *
);

# Setup variables to connect to DB
my $data_source = q/DBI:mysql:organizer;127.0.0.1;3306/;
my $user = q/root/;
my $password = q//;

# Connect to the data source and get a handle for that connection.
my $dbh = DBI->connect($data_source, $user, $password)
    or die "Can't connect to $data_source: $DBI::errstr";

# Inbox section
print "<h1>Inbox</h1>";
print "<h6>Update in the morning</h3>";

print(  q*
<div class="row">
<div class="nine columns">
<input class="u-full-width" type="text" placeholder="New todo item …" id="todo_input">
</div>
<div class="three columns">
  <input class="button-primary" type="submit" value="Add" id="add">
</div>
</div>
        *
);

my $sth = $dbh->prepare("SELECT message FROM inbox INNER JOIN todos ON todos.todo_id=inbox.todo_id")
                   or die "prepare statement failed: $dbh->errstr()";

$sth->execute() or die "execution failed: $dbh->errstr()"; 

my $sth_check = $dbh->prepare("SELECT COALESCE(is_done, 0) FROM inbox INNER JOIN todos ON todos.todo_id=inbox.todo_id")
                   or die "prepare statement failed: $dbh->errstr()";

$sth_check->execute() or die "execution failed: $dbh->errstr()"; 

my($lname,$fname,$ext);
my $checked;

print(q*<ul class="task-list" id="inbox">*);
# loop through each row of the result set, and print it
while(($lname,$fname,$ext) = $sth->fetchrow()){
   $checked = $sth_check->fetchrow();
   if ($checked == 0)
   {
       print(q?<li class="box" draggable=true><input class="is_done" type="checkbox" id="? . $lname . $fname . $ext . q?"/>?);
   }
   if ($checked == 1)
   {
       print(q?<li class="box" draggable=true><input class="is_done" type="checkbox" id="? . $lname . $fname . $ext . q?" checked />?);
   }
   print(" $lname $fname\t$ext\n");
   print("</li>")
}
print("</ul>");

print "<h6>#calls #atComputer #errands #office #atHome #agendas #read</h3>";

# Action section 
print "<h1>Action</h1>";
print "<h6>Assign time. Revisit. Flag what needs to be done today. The battle is to remember what to do!</h3>";

$sth = $dbh->prepare("SELECT message FROM action INNER JOIN todos ON todos.todo_id=action.todo_id")
                   or die "prepare statement failed: $dbh->errstr()";

$sth->execute() or die "execution failed: $dbh->errstr()"; 

print(q*<ul id="action" class="task-list">*);
# loop through each row of the result set, and print it
while(($lname,$fname,$ext) = $sth->fetchrow()){
   print(q?<li><input type="checkbox" disabled="" />?);
   print(" $lname $fname\t$ext\n");
   print("</li>")
}
print("</ul>");

# Wait section 
print "<h1>Wait</h1>";
print "<h6>Deffered actions. Waiting for the right time or on other people</h3>";

$sth = $dbh->prepare("SELECT message FROM wait INNER JOIN todos ON todos.todo_id=wait.todo_id")
                   or die "prepare statement failed: $dbh->errstr()";

$sth->execute() or die "execution failed: $dbh->errstr()"; 

print(q*<ul class="task-list" id="wait">*);
# loop through each row of the result set, and print it
while(($lname,$fname,$ext) = $sth->fetchrow()){
   print(q?<li><input type="checkbox" disabled="" />?);
   print(" $lname $fname\t$ext\n");
   print("</li>")
}
print("</ul>");

# Long term plan section 
print "<h1>Long term plan</h1>";
print "<h6>Update Weekly</h3>";

$sth = $dbh->prepare("SELECT message FROM long_term INNER JOIN todos ON todos.todo_id=long_term.todo_id")
                   or die "prepare statement failed: $dbh->errstr()";

$sth->execute() or die "execution failed: $dbh->errstr()"; 

print(q*<ul class="task-list" id="long-term">*);
# loop through each row of the result set, and print it
while(($lname,$fname,$ext) = $sth->fetchrow()){
   print(q?<li><input type="checkbox" disabled="" />?);
   print(" $lname $fname\t$ext\n");
   print("</li>")
}
print("</ul>");

$sth->finish();
$dbh->disconnect();

